steps:
  # Build the Docker image (explicitly for linux/amd64)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform'
      - 'linux/amd64'
      - '--no-cache'
      - '-t'
      - '${_IMAGE_NAME}:${COMMIT_SHA}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '.'

  # Verify the image contents
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🔍 Verifying Docker image contents..."
        docker run --rm --entrypoint ls ${_IMAGE_NAME}:${COMMIT_SHA} -la /app/
        echo "🔍 Checking server.jar..."
        docker run --rm --entrypoint sh ${_IMAGE_NAME}:${COMMIT_SHA} -c "ls -la /app/server.jar"
        echo "🔍 Checking credentials..."
        docker run --rm --entrypoint sh ${_IMAGE_NAME}:${COMMIT_SHA} -c "test -f /app/serviceAccountKey.json && echo 'OK' || echo 'MISSING'"
        echo "🔍 Testing Java..."
        docker run --rm --entrypoint java ${_IMAGE_NAME}:${COMMIT_SHA} -version
        echo "🔍 Checking architecture..."
        docker run --rm --entrypoint uname ${_IMAGE_NAME}:${COMMIT_SHA} -m
        echo "🔍 Testing JAR manifest..."
        docker run --rm --entrypoint sh ${_IMAGE_NAME}:${COMMIT_SHA} -c "unzip -p /app/server.jar META-INF/MANIFEST.MF | head -10"
        echo "✅ Verification complete"

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:${COMMIT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_IMAGE_NAME}:${COMMIT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "FIREBASE_CONFIG_PATH=/app/serviceAccountKey.json" \
          --timeout 300 \
          --cpu-boost \
          --min-instances 0 \
          --max-instances 10 \
          --memory 512Mi \
          --port 8080

substitutions:
  _SERVICE_NAME: ticker-wire-server
  _REGION: europe-west1
  _IMAGE_NAME: europe-west1-docker.pkg.dev/ticker-wire/cloud-run-source-deploy/ticker-wire-server

options:
  logging: CLOUD_LOGGING_ONLY
